# Generated by Django 5.2.15 on 2026-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studentprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="is_face_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="roll_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="university_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
