# Generated by Django 5.2.15 on 2026-06-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_studentprofile_face_encoding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="is_voice_registered",
            field=models.BooleanField(default=False),
        ),
    ]
