# Generated by Django 5.2.15 on 2026-06-28 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.teacherprofile"
            ),
        ),
    ]
