# Generated by Django 5.2.15 on 2026-07-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_subject_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_subjects", to="users.studentprofile"
            ),
        ),
    ]
