# Generated by Django 5.2.15 on 2026-07-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_attendancesession_attendancerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="voice_encoding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
